def/force-app/main/default/objects/StudentMaster__c/StudentMaster__c.object-meta.xml
<CustomObject>
    <label>StudentMaster</label>
    <nameField>
        <label>StudentName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

def/force-app/main/default/objects/StudentMaster__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

def/force-app/main/default/classes/studmastextension.cls
public class studmastextension {
    
    public  PageReference pg ;//redirect class
    public ApexPages.StandardController ourstdcontroller;//to access standard controller 
    public String stdName{get;set;}
    public Integer Age{get;set;}   
    public string myvariable{get;set;}
    public final studentmaster__c studmast;
    
    public studmastextension(ApexPages.StandardController stdController) 
    {
        system.debug('extension constructor');
        this.studmast = (studentmaster__c)stdController.getRecord();
        ourstdcontroller = stdController;//now i can use the standard controller methods in my  
        //extension class
        myvariable ='Walmart';
    }
    
    public PageReference saveandredirect(){
        system.debug(ourstdcontroller);
        
        ourstdcontroller.save();
        pg = new PageReference('/'+ this.studmast.id);
        pg.setRedirect(true);
        System.debug(this.studmast.id);
        return pg;
    }
    public PageReference saveandredirect2(){
        system.debug(this.studmast.Name);
     this.studmast.Name = stdname;
        this.studmast.age__C = Integer.valueOf(age);
       
        ourstdcontroller.save();
        pg = new PageReference('/'+ this.studmast.id);
        pg.setRedirect(true);
        
        return pg;
    }
    public string getWelcomeMsg ()
    {
        return 'Welcome' + studmast.name + 'to this session' ;
    }
}