def/force-app/main/default/objects/StudentMaster__c/StudentMaster__c.object-meta.xml
<CustomObject>
    <label>StudentMaster</label>
    <nameField>
        <label>StudentName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

def/force-app/main/default/objects/StudentMaster__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>Mech</fullName>
            </value>
            <value>
                <fullName>Phd1</fullName>
            </value>
            <value>
                <fullName>Phd2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

def/force-app/main/default/classes/studcustomcontroller.cls
public with sharing class studcustomcontroller {

    public   List<studentmaster__c> students {
        get{
         students  = Database.query('SELECT name, Department__c FROM studentmaster__c' );
         return students;
        }    
      set;}
    
      
    /*
    public List<studentmaster__c> getstudents() {
        //getstduents is the getter method. In the VF page refer to this as students dont use getstudents
        //
      List<studentmaster__c> students  = Database.query('SELECT name, Department__c FROM studentmaster__c' );
          return students;
    }*/
    
      public List<studentmaster__c>  checkit(){
        students  = Database.query('SELECT name, Department__c FROM studentmaster__c limit 3' );
        return students;
    }
  
}