def/force-app/main/default/objects/Offering__c/Offering__c.object-meta.xml
<CustomObject>
    <label>Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

def/force-app/main/default/objects/Offering__c/fields/Description_Text_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Text_Area__c</fullName>
    <label>Description Text Area</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

def/force-app/main/default/objects/Offering_Release__c/Offering_Release__c.object-meta.xml
<CustomObject>
    <label>Offering Release</label>
    <nameField>
        <label>Offering Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offering Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

def/force-app/main/default/objects/Offering_Release__c/fields/Offering_ID_Master_Detail_Rel__c.field-meta.xml
<CustomField>
    <fullName>Offering_ID_Master_Detail_Rel__c</fullName>
    <label>Offering ID Master Detail Rel</label>
    <referenceTo>Offering__c</referenceTo>
    <relationshipLabel>Offering Releases</relationshipLabel>
    <relationshipName>Offering_Releases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

def/force-app/main/default/objects/Offering_Release__c/fields/Release_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Release_Name_Text__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Release Name Text</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

def/force-app/main/default/classes/customController.cls
public with sharing class customController {

    public  List<Offering__c> offer { 
    get{
   List<Offering__c> offer1;
        offer1 = [Select id, Name,Description_Text_Area__c from Offering__c];
        return offer1;
    }  
    
     
    
    
     set; }
     
     public  List<Offering_Release__c> getofferrelease(String id)
     {
     
      List<Offering_Release__c> offerrelease;
      offerrelease = [Select Offering_ID_Master_Detail_Rel__r.Id, id, Name,Release_Name_Text__c from Offering_Release__c where Offering_ID_Master_Detail_Rel__r.Id = :id ];
        return offerrelease ;
    
        }
     
}