def/force-app/main/default/objects/Core_Team_Member__c/Core_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Core Team Member</label>
    <nameField>
        <label>Core Team Member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

def/force-app/main/default/objects/Core_Team_Member__c/fields/Offering_Release_ID_Master_Detail_Rel__c.field-meta.xml
<CustomField>
    <fullName>Offering_Release_ID_Master_Detail_Rel__c</fullName>
    <label>Offering Release ID Master Detail Rel</label>
    <referenceTo>Offering_Release__c</referenceTo>
    <relationshipLabel>Core Team Members</relationshipLabel>
    <relationshipName>Core_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

def/force-app/main/default/objects/Core_Team_Member__c/fields/Role_ID_Master_Detail_Rel__c.field-meta.xml
<CustomField>
    <fullName>Role_ID_Master_Detail_Rel__c</fullName>
    <label>Role ID Master Detail Rel</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Core Team Members</relationshipLabel>
    <relationshipName>Core_Team_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

def/force-app/main/default/objects/Core_Team_Member__c/fields/User_ID_Lookup_Rel__c.field-meta.xml
<CustomField>
    <fullName>User_ID_Lookup_Rel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User ID Lookup Rel</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Core_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

def/force-app/main/default/objects/Offering__c/Offering__c.object-meta.xml
<CustomObject>
    <label>Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

def/force-app/main/default/objects/Offering__c/fields/Description_Text_Area__c.field-meta.xml
<CustomField>
    <fullName>Description_Text_Area__c</fullName>
    <label>Description Text Area</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

def/force-app/main/default/objects/Offering_Release__c/Offering_Release__c.object-meta.xml
<CustomObject>
    <label>Offering Release</label>
    <nameField>
        <label>Offering Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offering Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

def/force-app/main/default/objects/Offering_Release__c/fields/Offering_ID_Master_Detail_Rel__c.field-meta.xml
<CustomField>
    <fullName>Offering_ID_Master_Detail_Rel__c</fullName>
    <label>Offering ID Master Detail Rel</label>
    <referenceTo>Offering__c</referenceTo>
    <relationshipLabel>Offering Releases</relationshipLabel>
    <relationshipName>Offering_Releases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

def/force-app/main/default/objects/Offering_Release__c/fields/Release_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Release_Name_Text__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Release Name Text</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

def/force-app/main/default/objects/Offering_Release__c/fields/Release_Version_Text__c.field-meta.xml
<CustomField>
    <fullName>Release_Version_Text__c</fullName>
    <label>Release Version Text</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

def/force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

def/force-app/main/default/classes/OfferOffereleaseVF_customController1.cls
public with sharing class OfferOffereleaseVF_customController1 {
    public String strX {
        get;set;
    }
    public String idd {
        get;set;
    }
    public String aName {
        get;set;
    }
    public String arvn {
        get;set;
    }
    public String arvt {
        get;set;
    }
    public String aparentoffer {
        get;set;
    }
    public Integer seqc {
        get;set;
    }
    public Offering_Release__c ofr;
    //within custom controller create variables including your lists
    //these list objects get invoked whenever the object name is invoked in apex tag value ={!varobject}
    public List < Offering__c > offer {
        get {
            List < Offering__c > offer1;
            offer1 = [Select id, Name, Description_Text_Area__c from Offering__c];
            return offer1;
        }
        set;
    }
    public List < Offering_Release__c > offerrelease1 {
        get {
           transient List < Offering_Release__c > offerrelease1;
            offerrelease1 = [Select Offering_ID_Master_Detail_Rel__r.Id, id, Name, Release_Name_Text__c from Offering_Release__c where Offering_ID_Master_Detail_Rel__r.Id = : strX];
            return offerrelease1;
        }
        set;
    }
    public List < Core_Team_Member__c > ctm {
        get {
           transient List < Core_Team_Member__c > ctm;
            ctm = [Select id, name, Role_ID_Master_Detail_Rel__c, User_ID_Lookup_Rel__r.Id, User_ID_Lookup_Rel__r.LastName, User_ID_Lookup_Rel__r.Username, Role_ID_Master_Detail_Rel__r.Name from Core_Team_Member__c where Offering_Release_ID_Master_Detail_Rel__r.Offering_ID_Master_Detail_Rel__r.Id = : strX];
            return ctm;
        }
        set;
    }
    public PageReference TestX() {
        strX = ApexPages.currentPage().getParameters().get('X');
        idd = strX;
        return null;
    }
    public PageReference TestX1() {
        // offerrelease1.add();
        ofr = new Offering_Release__c();
        ofr.Name = aName;
        ofr.Release_Name_Text__c = arvn;
        ofr.Release_Version_Text__c = arvt;
        ofr.Offering_ID_Master_Detail_Rel__c = idd;
        insert ofr;
        return null;
    }
}